project:
  type: website

website:
  site-url: https://verona-interfaces.github.io/metadata
  title: "Verona-Interfaces Metadata"
  favicon: favicon.ico
  page-navigation: true
  repo-url: https://github.com/verona-interfaces/metadata
  repo-actions: [issue]
  search: false
  navbar:
    pinned: true
    search: false
    logo: logo_verona_small.png
    right:
      - text: "Go to verona-interfaces"
        href: "https://verona-interfaces.github.io/"
  sidebar: 
    style: "docked"
    search: false
    contents:
      - href: index.qmd
        text: Home
      - href: docs/verona-module-metadata.qmd
        text: Metadata Specification
  page-footer:
    border: true
    background: light
    right:
      - text: "IQB 2024"
        href: https://www.iqb.hu-berlin.de
    left:
      - href: https://verona-interfaces.github.io
        text: Verona Interfaces

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    anchor-sections: true
