project:
  type: website

website:
  site-url: https://verona-interfaces.github.io/metadata
  title: "Verona Interfaces: Metadata"
  favicon: favicon.ico
  page-navigation: true
  repo-url: https://github.com/verona-interfaces/metadata
  repo-actions: [issue]
  search: false
  navbar:
    pinned: true
    search: false
    logo: logo_verona_small.png
    left:
      - text: Specification
        href: verona-module-metadata.qmd
    right:
      - text: "Verona Interfaces Home"
        href: "https://verona-interfaces.github.io/"
      - icon: github
        href: https://github.com/verona-interfaces/metadata
  page-footer:
    border: true
    background: light
    right:
      - text: "IQB 2024"
        href: https://www.iqb.hu-berlin.de
    left:
      - href: https://verona-interfaces.github.io
        text: Verona Interfaces Home

format:
  html:
    theme: pulse
    css: styles.css
    toc: true
    anchor-sections: true
