project:
  type: website

website:
  site-url: https://verona-interfaces.github.io/metadata
  title: "Verona-Interfaces Metadata"
  favicon: favicon.ico
  page-navigation: true
  repo-url: https://github.com/verona-interfaces/metadata
  repo-actions: [issue]
  navbar:
    pinned: true
    search: true
    logo: logo_verona_small.png
  page-footer:
    border: true
    background: light
    right:
      - text: "IQB 2024"
        href: https://www.iqb.hu-berlin.de
    left:
      - href: docs/verona-module-metadata.md
        text: Start

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    anchor-sections: true
    link-external-icon: true
    link-external-newwindow: true
